### ISSUE TITLE
(SP: 2) Add Interests step to student stepper

### ISSUE THREAD

**Issue by vlad-khrychov** [Space2Study-UA-1125/frontEnd#145]
UserStory: #62 
Blocked by: #143  , #141 

## Description
Add Interests step for student stepper by using implemented Subjects step of a tutor

## Design 
![Image](https://github.com/Space2Study-UA-1125/frontEnd/assets/67462207/8fb78e82-7d25-4d49-ba43-d292f94d8994)
## Acceptance Criteria
- [ ] When user clicks on field with categories they should be fetched from server
- [ ] When user chose a category and clicked on subjects select it should fetch all subjects of this category
- [ ] When user clicks on criss-cross of select it should clear it

**Comment by vldkk** [comment]
Implemented by Subjects step.
