### ISSUE TITLE
[Password reset] The “Email” input field is overlapped by description text.

### ISSUE THREAD

**Issue by online-marathon** [Space2Study-UA-1125/frontEnd#69]
**Description:** The “Email” input field is overlapped by description text on the password reset pop-up.

**Environment:** Windows 10 x64, Microsoft Edge 115.0.1901.203, Google Chrome 116.0.5845.96.

**Reproducible:** always.

**Build found:**

**Steps to reproduce:**
1. Click on the “Login” button on the header of the home page.
2. Click on the “Forgot password?” button on the “Password reset” pop-up.
3. Take a look at the “Email” input field.

**Actual result:**
The “Email” input field is overlapped by description text on the password reset pop-up.
![Image](https://github.com/Space2Study-UA-1125/frontEnd/assets/61456363/c75f9a62-7925-43ff-8b9f-a71264cc5378)

**Expected result:**
The “Email” input field is displayed aligned on the password reset pop-up.
![Image](https://github.com/Space2Study-UA-1125/frontEnd/assets/61456363/aac558f5-5fd7-4f21-b6e0-1866010a94f6)

**User story and test case links**
User Story User password reset #13

**Comment by holus-bolus** [comment]
Fixed the label displaying
